# We can raise our own exceptions (force them to happen) whenever we want, using the 'raise' keyword.We can also provide a specific message when raising an exception. raise ValueError('invalid character')
# print('Hello World')

# 'hello'[6]


# print("Goodbye")
